imports:
    - { resource: "@AdventureTimeBundle/Resources/config/characters.yml" }
    - { resource: "@AdventureTimeBundle/Resources/config/questions.yml" }
    - { resource: "@AdventureTimeBundle/Resources/config/codes.yml" }