services:
    model.user:
        class: AdventureTimeBundle\Model\UserModel
        arguments: [@doctrine.orm.entity_manager, @security.context, @session]

    model.security:
        class: AdventureTimeBundle\Model\SecurityModel
        arguments: ["@security.context", @doctrine.orm.entity_manager ,@model.user, @model.mail, @session]

    model.mail:
        class: AdventureTimeBundle\Model\MailModel
        arguments: [@mailer, %mailer_user%]

    model.profile:
        class: AdventureTimeBundle\Model\ProfileModel
        arguments: [@@doctrine.orm.entity_manager, @model.user]

    model.question:
        class: AdventureTimeBundle\Model\QuestionModel
        arguments: [@doctrine.orm.entity_manager]

    model.personage:
        class: AdventureTimeBundle\Model\PersonageModel
        arguments: [@doctrine.orm.entity_manager]

    get_set_method_normalizer:
         class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
         tags:
            - { name: serializer.normalizer }

    wsse.security.authentication.provider:
        class: AdventureTimeBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces", @session]

    wsse.security.authentication.listener:
        class: AdventureTimeBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]